"use client";

import React from "react";
import { Ban, Users, AlertTriangle, Shield } from "lucide-react";

interface PrintableSafetyReportProps {
  stats: {
    unsafe: number;
    borderline: number;
    blocked: number;
    handoffs: number;
    total: number;
    incidents: Array<{
      type: string;
      severity: string;
      timestamp: string;
      description: string;
    }>;
  };
}

export function PrintableSafetyReport({ stats }: PrintableSafetyReportProps) {
  return (
    <div
      id="safefier-report-print"
      style={{
        width: "800px",
        padding: "40px",
        backgroundColor: "#ffffff",
        color: "#000000",
        fontFamily: "Arial, sans-serif",
        border: "1px solid #d0d0d0",
        borderRadius: "8px",
        lineHeight: 1.5,
      }}
    >
      {/* ------------------------------------------------------------- */}
      {/* Header Section                                                 */}
      {/* ------------------------------------------------------------- */}
      <div style={{ marginBottom: "28px" }}>
        <h1
          style={{
            fontSize: "30px",
            margin: "0 0 4px 0",
            fontWeight: 700,
            letterSpacing: "0.5px",
          }}
        >
          Safefier Safety Report
        </h1>

        <p
          style={{
            fontSize: "14px",
            color: "#555",
            margin: 0,
          }}
        >
          Generated by Safefier — AI Safety Firewall
        </p>

        <hr
          style={{
            marginTop: "20px",
            border: "none",
            borderBottom: "1px solid #ccc",
          }}
        />
      </div>

      {/* ------------------------------------------------------------- */}
      {/* Summary Section                                                 */}
      {/* ------------------------------------------------------------- */}
      <h2
        style={{
          fontSize: "20px",
          marginBottom: "14px",
          fontWeight: 600,
        }}
      >
        Summary
      </h2>

      <table
        style={{
          width: "100%",
          borderCollapse: "collapse",
          marginBottom: "30px",
          fontSize: "14px",
        }}
      >
        <tbody>
          <tr>
            <td style={{ padding: "6px 0" }}>
              <Ban style={{ width: "16px", height: "16px", marginRight: "6px" }} />
              Unsafe Detected:
            </td>
            <td style={{ textAlign: "right" }}>{stats.unsafe}</td>
          </tr>

          <tr>
            <td style={{ padding: "6px 0" }}>
              <Users style={{ width: "16px", height: "16px", marginRight: "6px" }} />
              Human Handoffs:
            </td>
            <td style={{ textAlign: "right" }}>{stats.handoffs}</td>
          </tr>

          <tr>
            <td style={{ padding: "6px 0" }}>
              <AlertTriangle
                style={{ width: "16px", height: "16px", marginRight: "6px" }}
              />
              AI Blocked:
            </td>
            <td style={{ textAlign: "right" }}>{stats.blocked}</td>
          </tr>

          <tr>
            <td style={{ padding: "6px 0" }}>
              <Shield style={{ width: "16px", height: "16px", marginRight: "6px" }} />
              Monitoring Cases:
            </td>
            <td style={{ textAlign: "right" }}>{stats.borderline}</td>
          </tr>

          <tr>
            <td style={{ padding: "10px 0", fontWeight: "bold" }}>Total Messages:</td>
            <td style={{ textAlign: "right", fontWeight: "bold" }}>
              {stats.total}
            </td>
          </tr>
        </tbody>
      </table>

      <hr
        style={{
          margin: "26px 0",
          border: "none",
          borderBottom: "1px solid #ccc",
        }}
      />

      {/* ------------------------------------------------------------- */}
      {/* Incident Log Section                                           */}
      {/* ------------------------------------------------------------- */}
      <h2
        style={{
          fontSize: "20px",
          marginBottom: "14px",
          fontWeight: 600,
        }}
      >
        Incident Log
      </h2>

      {stats.incidents.length === 0 ? (
        <p style={{ color: "#555", fontSize: "14px" }}>No incidents detected.</p>
      ) : (
        <table
          style={{
            width: "100%",
            borderCollapse: "collapse",
            border: "1px solid #ddd",
            fontSize: "13px",
          }}
        >
          <thead>
            <tr style={{ backgroundColor: "#f7f7f7" }}>
              <th
                style={{
                  textAlign: "left",
                  padding: "10px",
                  border: "1px solid #ddd",
                }}
              >
                Type
              </th>
              <th
                style={{
                  textAlign: "center",
                  padding: "10px",
                  border: "1px solid #ddd",
                }}
              >
                Severity
              </th>
              <th
                style={{
                  textAlign: "center",
                  padding: "10px",
                  border: "1px solid #ddd",
                }}
              >
                Time
              </th>
              <th
                style={{
                  textAlign: "left",
                  padding: "10px",
                  border: "1px solid #ddd",
                  width: "60%",
                }}
              >
                Description
              </th>
            </tr>
          </thead>

          <tbody>
            {stats.incidents.map((incident, i) => (
              <tr key={i}>
                <td
                  style={{
                    padding: "10px",
                    border: "1px solid #ddd",
                  }}
                >
                  {incident.type}
                </td>
                <td
                  style={{
                    padding: "10px",
                    border: "1px solid #ddd",
                    textAlign: "center",
                    fontWeight: "bold",
                    textTransform: "uppercase",
                  }}
                >
                  {incident.severity}
                </td>
                <td
                  style={{
                    padding: "10px",
                    border: "1px solid #ddd",
                    textAlign: "center",
                  }}
                >
                  {incident.timestamp}
                </td>
                <td
                  style={{
                    padding: "10px",
                    border: "1px solid #ddd",
                  }}
                >
                  {incident.description}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
